version: "3.3"
services:
  router:
    image: nginx
    restart: always
    container_name: router
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./content:/srv/package/content
    ports:
      - 80:80
      - 4567:4567
    user: root
